######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 18 11:31:22 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GraphicsItemDev.hpp Widget.h
SOURCES += GraphicsItemDev.cpp main.cpp Widget.cpp
TARGET=./Debug/
CONFIG+=Debug
OBJECTS_DIR = ./build/obj/
MOC_DIR = build/moc/
UI_DIR=build/ui
QT += gui core sql xml
