#############################################################################
# Makefile for building: Debug/GraphicsItemDev
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Sep 25 14:33:06 2018
# Project:  GraphicsItemDev.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile GraphicsItemDev.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Ibuild/moc
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = GraphicsItemBF.cpp \
		GraphicsItemBN.cpp \
		GraphicsItemDev.cpp \
		main.cpp \
		Widget.cpp build/moc/moc_GraphicsItemBN.cpp
OBJECTS       = build/obj/GraphicsItemBF.o \
		build/obj/GraphicsItemBN.o \
		build/obj/GraphicsItemDev.o \
		build/obj/main.o \
		build/obj/Widget.o \
		build/obj/moc_GraphicsItemBN.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		GraphicsItemDev.pro
QMAKE_TARGET  = GraphicsItemDev
DESTDIR       = Debug/
TARGET        = Debug/GraphicsItemDev

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Debug/ || $(MKDIR) Debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GraphicsItemDev.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile GraphicsItemDev.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile GraphicsItemDev.pro

dist: 
	@$(CHK_DIR_EXISTS) build/obj/GraphicsItemDev1.0.0 || $(MKDIR) build/obj/GraphicsItemDev1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/obj/GraphicsItemDev1.0.0/ && $(COPY_FILE) --parents GraphicsItemBF.hpp GraphicsItemBN.hpp GraphicsItemDev.hpp Widget.h build/obj/GraphicsItemDev1.0.0/ && $(COPY_FILE) --parents GraphicsItemBF.cpp GraphicsItemBN.cpp GraphicsItemDev.cpp main.cpp Widget.cpp build/obj/GraphicsItemDev1.0.0/ && (cd `dirname build/obj/GraphicsItemDev1.0.0` && $(TAR) GraphicsItemDev1.0.0.tar GraphicsItemDev1.0.0 && $(COMPRESS) GraphicsItemDev1.0.0.tar) && $(MOVE) `dirname build/obj/GraphicsItemDev1.0.0`/GraphicsItemDev1.0.0.tar.gz . && $(DEL_FILE) -r build/obj/GraphicsItemDev1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc/moc_GraphicsItemBN.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_GraphicsItemBN.cpp
build/moc/moc_GraphicsItemBN.cpp: GraphicsItemBN.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) GraphicsItemBN.hpp -o build/moc/moc_GraphicsItemBN.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: build/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/obj/GraphicsItemBF.o: GraphicsItemBF.cpp GraphicsItemBF.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GraphicsItemBF.o GraphicsItemBF.cpp

build/obj/GraphicsItemBN.o: GraphicsItemBN.cpp GraphicsItemBN.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GraphicsItemBN.o GraphicsItemBN.cpp

build/obj/GraphicsItemDev.o: GraphicsItemDev.cpp GraphicsItemDev.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GraphicsItemDev.o GraphicsItemDev.cpp

build/obj/main.o: main.cpp Widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o main.cpp

build/obj/Widget.o: Widget.cpp Widget.h \
		GraphicsItemDev.hpp \
		GraphicsItemBN.hpp \
		GraphicsItemBF.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Widget.o Widget.cpp

build/obj/moc_GraphicsItemBN.o: build/moc/moc_GraphicsItemBN.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_GraphicsItemBN.o build/moc/moc_GraphicsItemBN.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

